language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t googoo99/food -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true googoo99/food npm run test

after_success:
  - docker build -t googoo99/docker-frontend ./frontend
  - docker build -t googoo99/docker-backend ./backend
  - docker build -t googoo99/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push googoo99/docker-frontend
  - docker push googoo99/docker-backend
  - docker push googoo99/docker-nginx

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
  region: "ap-northeast-2"
  app: "food"
  env: "food-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-104900351462"
  on:
    branch: main