language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t choiyongsik/Food -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true choiyongsik/Food npm run test

after_success:
  - docker build -t choiyongsik/docker-frontend ./frontend
  - docker build -t choiyongsik/docker-backend ./backend 
  - docker build -t choiyongsik/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push choiyongsik/docker-frontend
  - docker push choiyongsik/docker-backend
  - docker push choiyongsik/docker-nginx
