version: '3.8'
services:
    nginx:
        container_name: nginx
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports: 
            - "3000:80"
        links:
            - frontend
            - backend
        networks:
            - default-network

    frontend:
        container_name: frontend-react
        build:
            dockerfile: Dockerfile.dev
            context: ./frontend
        volumes:
            - /app/node_modules
            - ./frontend:/app
        stdin_open: true
        networks:
            - default-network

    backend:
        container_name: backend-node
        build: 
            dockerfile: Dockerfile.dev
            context: ./backend
        volumes:
            - /app/node_modules
            - ./backend:/app
        networks:
            - default-network
     environment:
       MYSQL_HOST: mysql
       MYSQL_USER: admin
       MYSQL_ROOT_PASSWORD: rnrn11!!
       MYSQL_DATABASE: food
       MYSQL_PORT: 3306

networks:
    default-network:
        driver: bridge
